version: "3.8"

services:
  app:
    build: ./
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    links:
      - postgres
    profiles: ["app"]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./sql/docker/init.sql:/docker-entrypoint-initdb.d/create_database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
